coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch:
      default:
        target: 70%
  precision: 1
  round: down
  range: "40...70"

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true
